name: Update libraries from npm
on:
  schedule:
    - cron: '0 0 1 */3 *'
  workflow_dispatch:
env:
  CONFIG_PATH: ./assets/lib/librarybot.yml
permissions:
  contents: write
  pull-requests: write
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      libraries: ${{ steps.list.outputs.libraries_json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: List libraries
        id: list
        uses: hugo-fixit/librarybot@v1
        with:
          mode: list
          config_path: ${{ env.CONFIG_PATH }}
  update:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        library: ${{ fromJson(needs.prepare.outputs.libraries) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Update library
        id: update
        uses: hugo-fixit/librarybot@v1
        with:
          mode: update
          library: ${{ matrix.library }}
          config_path: ${{ env.CONFIG_PATH }}
      - name: Create Pull Request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          title: 'chore(deps): bump ${{ steps.update.outputs.package }} from `${{ steps.update.outputs.from_version }}` to `${{ steps.update.outputs.to_version }}`'
          commit-message: 'chore(deps): bump ${{ steps.update.outputs.package }} from `${{ steps.update.outputs.from_version }}` to `${{ steps.update.outputs.to_version }}`'
          body: |
            Automated update of `${{ steps.update.outputs.package }}` from `${{ steps.update.outputs.from_version }}` to `${{ steps.update.outputs.to_version }}`.
          branch: ${{ steps.update.outputs.pr_branch }}
          base: main
          labels: dependencies
          reviewers: Lruihao
