name: FixIt Test Build
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Actions-Hugo-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ vars.HUGO_VERSION || 'latest' }}
          extended: true
      - name: Build Hugo static files
        run: hugo --source=test --themesDir ../.. --theme $PWD --gc --minify --logLevel info
